const notificationChannelKey = 'mytube_downloads_channel';
const notificationChannelName = 'Downloads Channel';
const notificationChannelDescription = 'Shows the progress of downloads';

const Map<String, String> countryToLanguage = {
  'US': 'en',
  'GB': 'en',
  'IT': 'it',
  'FR': 'fr',
  'ES': 'es',
  'DE': 'de',
  'RU': 'ru',
  'JP': 'ja',
  'CN': 'zh',
  'IN': 'hi',
  'BR': 'pt',
  'MX': 'es',
  'CA': 'en',
  'AU': 'en',
  'KR': 'ko',
  'TR': 'tr',
  'ID': 'id',
  'NL': 'nl',
  'SE': 'sv',
  'PL': 'pl',
  'RO': 'ro',
  'CZ': 'cs',
  'PT': 'pt',
  'VN': 'vi',
  'TH': 'th',
  'AR': 'es',
  'HK': 'zh',
  'DK': 'da',
  'FI': 'fi',
  'NO': 'nb',
  'BE': 'nl',
};
